[package]
name = "lwoss"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version="0.6", features = ["http2"]}
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
