name: Build

on:
  create:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on:  ${{ matrix.os }}

    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: actions/checkout@v3

      - run: cargo build --release
