name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: python --version

      # Build the server
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: cargo build --release

      # Build the web app
      - uses: actions/cache@v3
        id: cache-web
        with:
          path: web/build
          key: pages-${{ github.sha }}
          enableCrossOsArchive: true

      - uses: pnpm/action-setup@v2
        if: steps.cache-web.outputs.cache-hit != 'true'
        with:
          version: latest
          run_install: |
            - cwd: web

      - run: pnpm run build
        if: steps.cache-web.outputs.cache-hit != 'true'
        working-directory: web

      # Pack and deploy
      - run: node move-files.mjs
