name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on:  ${{ matrix.os }}

    steps:
      # Build the server
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: actions/checkout@v3

      - run: cargo build --release

      # Build the web app
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install:
            cwd: web

      - run: pnpm run build
        working-directory: web
