name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test
        env:
          RUSTFLAGS: -Cinstrument-coverage

      - uses: actions-rs/grcov@v0.1

      - uses: codecov/codecov-action@v3
